API проекта Mesto. Централизованная обработка ошибок и валидация запросов.
romcath/praktikum_backend-mesto pull request #4
Opened 2020-04-16 19:23 UTC by romcath

Добрый день!

**Реализована логика:**
- [x] к серверу можно обратиться по IP-адресу ```84.201.167.230``` и доменному имени ```mesto.ga```;
- [x] к серверу можно обратиться по ```http``` и по ```https```;
- [x] все ошибки обрабатываются централизованно;
- [x] тела запросов, заголовки и параметры, валидируются по определённым схемам;
- [x] все запросы и ответы записываются в файл ```request.log```;
- [x] все ошибки записываются в файл ```error.log```;
- [x] файлы логов не добавляются в репозиторий;
- [x] сервер самостоятельно восстанавливается после GET-запроса на URL ```/crash-test```.

2020-04-17 16:48 UTC, aarefiev requested changes
Добрый вечер.

Отличная работа. Выполнено дополнительное задание :rocket: :+1: :1st_place_medal: .

Отличное описание проекта :+1: :+1: :+1: . Проект хорошо структурирован, элементы сгруппированы в группы по принадлежности (роуты, контроллеры, модели, мидлвары, модули ошибок) :feelsgood: :+1: . Для статической проверки синтаксиса подключен линтер `eslint`, устанавливающий соответствие стайлгайду _Airbnb_. Запуск линтера завершается без ошибрк :+1: . Для роутов назначена валидация, валидация соответствует заданию и схемам моделей :+1: . Есть проблема с обработкой нештатных ситуаций при регистрации :bug: . Есть обработка краш-теста, сервер сам восстанавливает работоспособность  :+1: . Корректно работает централизованный обработчик ошибок, обработчик несуществующего роута, мидлвара авторизации :+1: . Запросы логируются в `request.log`, ошибки в `error.log` :+1: . Временные файлы игнорируются :+1: . Сервер локально запускается с хот релоадом и без :+1: . Публичный сервер открывается по IP-адресу и по доменному имени по протоколам `HTTP` и `HTTPS` :+1: . На сегодня сертификат валиден :+1: . Секретный ключ на публичном сервере отличается от используемого локально :+1:.

Судя по описанию выше ошибок практически нет, это очень круто. Но есть места для улучшений. Краткий список представлен ниже, расширенные комментарии представлены непосредственно в коде.

**Нужно исправить:** при возникновении ошибки при создании пользователя возвращается 400.

**Можно лучше:**
1. Использовать встроенные хелперы `mongoose` для обработки несуществующей записи.
2. Использовать единый `.catch()` блок для вложенных промисов.
3. Вынести настройки в отдельный конфигурационный файл.
4. Не обязательно отправлять код ошибки в теле ответа.
5. Бросать осмысленные исключения.

2020-04-17 16:48 UTC, aarefiev commented on controllers/cards.js
>        }
Можно лучше: использовать встроенные хелперы `mongoose` для обработки несуществующей записи.
В `mongoose` по-умолчанию методы, которые делают выборку значений из базы данных по какому-то условию, возвращают `null` в случае отсутствия записи в базе данных. Для того, чтобы отловить эту ситуацию есть хелпер [`.orFail()`](https://mongoosejs.com/docs/api.html#query_Query-orFail).

Хелпер принимает ошибку или функцию, которая её возвращает. Во время срабатывания хелпера происходит отклонение промиса (_reject_), а переданное значение будет возвранео в `.catch()` блок в качестве причины.

2020-04-17 16:48 UTC, aarefiev commented on controllers/cards.js
>          .then(() => res.send({ data: card }));
Можно лучше: использовать единый `.catch()` блок для вложенных промисов.
Особенность работы промисов в том, что `.then()` блоки выполняются в том порядке, в котором они были описаны. Причем вызов следующего `.then()` запускается только после того как промис перейдет в состояние выполнен (_resolved_) или как текущий `.then()` блок будет выполнен. Это означает, что вложенный промис и его `.then()` блоки тоже могут быть встроены в цепочку вызовов, если внутри `.then()` блока будет выполнен `return`.
При наличии одной цепочки вложенный `.catch()` блок можно убирать, потому что любое отклонение промиса (_reject_) будет поймано верхнеуровневым `.catch()` блоком.

```suggestion
      return Card.deleteOne(card)
        .then(() => res.send({ data: card }));
```

2020-04-17 16:48 UTC, aarefiev commented on controllers/cards.js
>        }
Можно лучше: использовать встроенные хелперы `mongoose` для обработки несуществующей записи.

2020-04-17 16:48 UTC, aarefiev commented on controllers/cards.js
>        }
Можно лучше: использовать встроенные хелперы `mongoose` для обработки несуществующей записи.

2020-04-17 16:48 UTC, aarefiev commented on controllers/users.js
>        }
Можно лучше: использовать встроенные хелперы `mongoose` для обработки несуществующей записи.

2020-04-17 16:48 UTC, aarefiev commented on controllers/users.js
>        const token = jwt.sign({ _id: user._id }, NODE_ENV === 'production' ? JWT_SECRET : 'dev-secret');
Можно лучше: вынести настройки в отдельный конфигурационный файл.
По аналогии с портом, на котором будет запущен сервер и адресом для подключения к базе данных, секретный ключ можно также рассматривать как настройку. Поэтому его спокойно можно выносить в `config.js`.

2020-04-17 16:48 UTC, aarefiev commented on models/user.js
>        }
Можно лучше: использовать встроенные хелперы `mongoose` для обработки несуществующей записи.

2020-04-17 16:48 UTC, aarefiev commented on models/user.js
>        }
Можно лучше: бросать осмысленные исключения.
Например, можно бросить исключение с ошибкой `UnauthorizedError`, потому что пользователь не был найден в базе данных. Это также позволит избавиться от фиксирования возвращаемой ошибки при обработке ошибок::
https://github.com/romcath/praktikum_backend-mesto/blob/e3120167803d4d96cac1a29d7efcb41be7aa6e9c/controllers/users.js#L71
Например, если возникнут ошибки связанные с кодом, типа `SyntaxError` или `TypeError` обработчик вернёт ошибку 401, что будет не совсем корректным в этой ситуации.

2020-04-17 16:48 UTC, aarefiev commented on models/user.js
>            }
Можно лучше: бросать осмысленные исключения.

2020-04-17 16:48 UTC, aarefiev commented on middlewares/errorHandler.js
> +      status: statusCode,
Можно лучше: не обязательно отправлять код ошибки в теле ответа.
Код ошибки уже есть в заголовке `Status`.

2020-04-17 16:48 UTC, aarefiev commented on controllers/users.js
> +    .catch(() => next(new BadRequestError(`Почта ${email} уже используется`)));
Нужно исправить: при возникновении ошибки при создании пользователя возвращается 400.
Во первых, [400 Bad Request](url) - это всегда про ошибку в пользовательских данных. Так как у нас есть валидация на уровне роутинга, мы можем со 100% вероятностью сказать, что данные верны. Поэтому в контроллере никогда не может быть 400 ошибки.
Во вторых, при создании пользователя можешь быть минимум две ошибочные ситуации. Первая - это ошибка связанная с кодом или с сервером (например, `SyntaxError` или `TypeErrror` или база данных не отвечает), вторая - это ошибка уникальности данных. Вот здесь уже ожидается [409 Conflict](https://developer.mozilla.org/ru/docs/Web/HTTP/Status/409).

2020-04-17 20:00 UTC, romcath commented
@aarefiev спасибо за подробное ревью!
Исправила ошибки.

2020-04-18 16:33 UTC, aarefiev approved these changes
Отлично, ошибки исправлены. Новых не обнаружено. Работа принимается. :rocket: 
Хотя по улучшениям ещё остались вопросы, поэтому я по ним дополнительно прошелся.

**Можно лучше:**
1. Вынести настройки в отдельный конфигурационный файл.
2. Избавиться от фиксирования возвращаемой ошибки при обработке ошибок.
3. Бросать осмысленные исключения.

2020-04-18 16:33 UTC, aarefiev commented on controllers/users.js
> +      const token = jwt.sign({ _id: user._id }, NODE_ENV === 'production' ? JWT_SECRET : SECRET);
Можно лучше: вынести настройки в отдельный конфигурационный файл.
Я имел ввиду вынести полностью `NODE_ENV === 'production' ? JWT_SECRET : SECRET`. В управляющем коде нам нужен просто секретный ключ, тут не важно как он был получен. Да и код сократится:
```suggestion
      const token = jwt.sign({ _id: user._id }, JWT_SECRET);
```

Актуально и для:
https://github.com/romcath/praktikum_backend-mesto/blob/15990bb6c12ac89f0efba7e3319600f2546f3658/middlewares/auth.js#L15

2020-04-18 16:33 UTC, aarefiev commented on models/user.js
> +    .orFail()
Можно лучше: бросать осмысленные исключения.
Не хватает `UnauthorizedError`, а то ошибка будет обработана не как ошибка авторизации, а как ошибка на сервере (Internal Server Error).

2020-04-18 16:33 UTC, aarefiev commented on controllers/users.js
>      .catch(() => next(new UnauthorizedError('Неправильные почта или пароль')));
Можно лучше: избавиться от фиксирования возвращаемой ошибки при обработке ошибок.
Если метод `findUserByCredentials()` отклонит обещание по причине неправильной пары логин/пароль, то вернётся 401:
https://github.com/romcath/praktikum_backend-mesto/blob/15990bb6c12ac89f0efba7e3319600f2546f3658/models/user.js#L45-L48
Тоже самое произойдёт, если пользователь не был найден в базе данных (конечно если в `orFail()` всё-таки будет добавлена отправка `UnauthorizedError`).
Ну а ошибки типа `SyntaxError`, `TypeError` обрабатываются централизованным обработчиком ошибок. Поэтому можно:
```suggestion
    .catch(next);
```

2020-04-18 19:23 UTC, merged